language: android
dist: trusty
android:
  components:
    - build-tools-28.0.3
    - android-28
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    -
    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-28
    # - sys-img-x86-android-17
licenses:
  - android-sdk-license-.+

# Emulator Management: Create, Start and Wait
#before_script:
#  - echo no | android create avd --force -n test -t android-28 --abi armeabi-v7a
#  - emulator -avd test -no-skin -no-audio -no-window &
#  - android-wait-for-emulator
#  - adb shell input keyevent 82 &

addons:
  sonarcloud:
    organization: grishberg
    token:
      secure: "n7MhUSRcOPPKKGxDjMVRxMLnlCW29SvvWB34qc65r7/Kz3NBX52waMgLwUbxhumLLXac2GuCM7pojBr3KMhXaKa+qcoWas7yXlwLymJPqQClwygqqTyQc/2cMDb59FVanP/JiTK7aVhdhLhJBD23QyoZ7qiYlsq16l8Dmg/DPvZqDbv/Pb0Odw/LBPGS4eTGmv26IjsP2zdo+59R4Jdh1dC5PcoUQDuNJZ3CcPJotB41dkCLL26RWDhtzEZIrEYj7J6hWq1ij7Ie7frJx8v0DNolCb6ilkvMz3l3YJVAATP9oCjpTNQKgirkT6GGr0hzRNUS2J5mHQREZOKwemR73S/SJ3brey39Q9U60/FwHMUBNUcJie/mcjRyyym3JXgM+bwrfuZ3VB3qNk5/9C4srdPVNuPY8f6cUIcUlkgiO6bL/JGLqdKAxkkk9vO1pzRPnvZnU/5L4D6Y/7eWO8skMO5IiUDHioEwbqM8BDOBIXTFWv8Yq7MRbc1J86l0czDhmoPdLHJWC60wLSSutBt05pK0Yy0Ly03hX9yOZVpuFCxOtf9bD1/oyEkOurs6xmuhgPb0Uizns25oR5reyUWhLCaoCFMs27sGECFX4dx0/WheRWeMs33NV1uAe67RCtwWjMu3pk7ZbXTeIJK63PUGW5Zf20xIhvOELulgoC5rzXE="
    branches:
      - master
      - ".*"
    script:
      - "./gradlew sonarqube"
after_success:
  - mvn clean test jacoco:report coveralls:jacoco

# Deploy with gradle task
deploy:
  provider: script
  script: ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    branch: master
    # tags: true - for deploying only for tagged commit

env:
  global:
    # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8
